using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text;

namespace AXTConverter.Models
{
    
    [Table("AXTUpload")]
    public class AXTModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string PatientLastName { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientID { get; set; }
        public string PatientsBirthDate { get; set; }
        public string PatientsSex { get; set; }
        public string PatientComments { get; set; }
        public string StudyDate { get; set; }
        public string StudyTime { get; set; }
        public string AccessionNumber { get; set; }
        public string ReferringPhysiciansName { get; set; }
        public string StudyID { get; set; }
        public string StudyDescription { get; set; }
        public string ReaderLastName { get; set; }
        public string PrintedSignatureName { get; set; }
        public string ReaderIDNumber { get; set; }
        public string ReaderInitials { get; set; }
        public string ReaderStreetAddress { get; set; }
        public string ReaderCity { get; set; }
        public string ReaderState { get; set; }
        public string ReaderZipCode { get; set; }
        public string FORM_NBR { get; set; }
        public string XRAY_DATE { get; set; }
        public string WORKER_SSN { get; set; }
        public string ClientName { get; set; }
        public string ClientStreetAddress { get; set; }
        public string ClientCity { get; set; }
        public string ClientState { get; set; }
        public string ClientZipCode { get; set; }
        public string ClientPhone { get; set; }
        public string ClientOtherContactInfo { get; set; }
        public string FACILITY_NBR { get; set; }
        public string READ_TYPE { get; set; }
        public string FILM_QUALITY { get; set; }
        public string UNREAD_OVEREXPOSED { get; set; }
        public string UNREAD_UNDEREXPOSED { get; set; }
        public string UNREAD_ARTIFACTS { get; set; }
        public string UNREAD_POSITION { get; set; }
        public string UNREAD_CONTRAST { get; set; }
        public string UNREAD_PROCESSING { get; set; }
        public string UNREAD_UNDERINFLATION { get; set; }
        public string UNREAD_MOTTLE { get; set; }
        public string UNREAD_EDGE { get; set; }
        public string UNREAD_OTHER { get; set; }
        public string UNREAD_OTHER_COMMENT { get; set; }
        public string Q2A { get; set; }
        public string SMALL_OPAC_PRI_TYPE { get; set; }
        public string SMALL_OPAC_SEC_TYPE { get; set; }
        public string SMALL_OPAC_ZONE_UR { get; set; }
        public string SMALL_OPAC_ZONE_UL { get; set; }
        public string SMALL_OPAC_ZONE_MR { get; set; }
        public string SMALL_OPAC_ZONE_ML { get; set; }
        public string SMALL_OPAC_ZONE_LR { get; set; }
        public string SMALL_OPAC_ZONE_LL { get; set; }
        public string SMALL_OPAC_CATEGORY { get; set; }
        public string LARGE_OPAC_STAGE { get; set; }
        public string Q3A { get; set; }
        public string PLEURAL_SITE_PROFILE { get; set; }
        public string PLEURAL_SITE_FACE { get; set; }
        public string PLEURAL_SITE_DIAPHRAGM { get; set; }
        public string PLEURAL_SITE_OTHER { get; set; }
        public string PLEURAL_CALC_PROFILE { get; set; }
        public string PLEURAL_CALC_FACE { get; set; }
        public string PLEURAL_CALC_DIAPHRAGM { get; set; }
        public string PLEURAL_CALC_OTHER { get; set; }
        public string PLEURAL_EXTENT_R { get; set; }
        public string PLEURAL_EXTENT_R_123 { get; set; }
        public string PLEURAL_EXTENT_L { get; set; }
        public string PLEURAL_EXTENT_L_123 { get; set; }
        public string PLEURAL_WIDTH_R { get; set; }
        public string PLEURAL_WIDTH_R_ABC { get; set; }
        public string PLEURAL_WIDTH_L { get; set; }
        public string PLEURAL_WIDTH_L_ABC { get; set; }
        public string Q3C { get; set; }
        public string DIFFUSE_SITE_PROFILE { get; set; }
        public string DIFFUSE_SITE_FACE { get; set; }
        public string DIFFUSE_CALC_PROFILE { get; set; }
        public string DIFFUSE_CALC_FACE { get; set; }
        public string DIFFUSE_EXTENT_R { get; set; }
        public string DIFFUSE_EXTENT_R_123 { get; set; }
        public string DIFFUSE_EXTENT_L { get; set; }
        public string DIFFUSE_EXTENT_L_123 { get; set; }
        public string DIFFUSE_WIDTH_R { get; set; }
        public string DIFFUSE_WIDTH_R_ABC { get; set; }
        public string DIFFUSE_WIDTH_L { get; set; }
        public string DIFFUSE_WIDTH_L_ABC { get; set; }
        public string Q4A { get; set; }
        public string OTHER_SYMBOLS_AA { get; set; }
        public string OTHER_SYMBOLS_AT { get; set; }
        public string OTHER_SYMBOLS_AX { get; set; }
        public string OTHER_SYMBOLS_BU { get; set; }
        public string OTHER_SYMBOLS_CA { get; set; }
        public string OTHER_SYMBOLS_CG { get; set; }
        public string OTHER_SYMBOLS_CN { get; set; }
        public string OTHER_SYMBOLS_CO { get; set; }
        public string OTHER_SYMBOLS_CP { get; set; }
        public string OTHER_SYMBOLS_CV { get; set; }
        public string OTHER_SYMBOLS_DI { get; set; }
        public string OTHER_SYMBOLS_EF { get; set; }
        public string OTHER_SYMBOLS_EM { get; set; }
        public string OTHER_SYMBOLS_ES { get; set; }
        public string OTHER_SYMBOLS_FR { get; set; }
        public string OTHER_SYMBOLS_HI { get; set; }
        public string OTHER_SYMBOLS_HO { get; set; }
        public string OTHER_SYMBOLS_ID { get; set; }
        public string OTHER_SYMBOLS_IH { get; set; }
        public string OTHER_SYMBOLS_KL { get; set; }
        public string OTHER_SYMBOLS_ME { get; set; }
        public string OTHER_SYMBOLS_PA { get; set; }
        public string OTHER_SYMBOLS_PB { get; set; }
        public string OTHER_SYMBOLS_PI { get; set; }
        public string OTHER_SYMBOLS_PX { get; set; }
        public string OTHER_SYMBOLS_RA { get; set; }
        public string OTHER_SYMBOLS_RP { get; set; }
        public string OTHER_SYMBOLS_TB { get; set; }
        public string SEE_DR { get; set; }
        public string DATE_DR_NOTIFIED { get; set; }
        public string READ_DATE { get; set; }
        public string OTHER_DISEASES { get; set; }
        public string OTHER_DISEASES_EVENTRATION { get; set; }
        public string OTHER_DISEASES_HIATAL_HERNIA { get; set; }
        public string OTHER_DISEASES_BRONCHOVASCULAR { get; set; }
        public string OTHER_DISEASES_HYPERINFLATION { get; set; }
        public string OTHER_DISEASES_BONY_CHEST_CAGE { get; set; }
        public string OTHER_DISEASES_FRACTURE_HEALED { get; set; }
        public string OTHER_DISEASES_FRACTURE_NONHEALED { get; set; }
        public string OTHER_DISEASES_SCOLIOSIS { get; set; }
        public string OTHER_DISEASES_VERTEBRAL_COLUMN { get; set; }
        public string OTHER_DISEASES_AZYGOS_LOBE { get; set; }
        public string OTHER_DISEASES_LUNG_DENSITY { get; set; }
        public string OTHER_DISEASES_INFILTRATE { get; set; }
        public string OTHER_DISEASES_NODULAR_LESION { get; set; }
        public string OTHER_DISEASES_FOREIGN_BODY { get; set; }
        public string OTHER_DISEASES_POST_SURGICAL { get; set; }
        public string OTHER_DISEASES_CYST { get; set; }
        public string OTHER_DISEASES_AORTA_ANOMALY { get; set; }
        public string OTHER_DISEASES_VASCULAR { get; set; }
        public string OTHER_COMMENTS { get; set; }
        public string Modality { get; set; }
        public string SeriesNumber { get; set; }
        public string Laterality { get; set; }
        public string SeriesDate { get; set; }
        public string SeriesTime { get; set; }
        public string ProtocolName { get; set; }
        public string SeriesDescription { get; set; }
        public string BodyPartExamined { get; set; }
        public string PatientPosition { get; set; }
        public string PatientOrientation { get; set; }
        public string InstanceNumber { get; set; }
        public string ContentDate { get; set; }
        public string ContentTime { get; set; }
        public string AcquisitionNumber { get; set; }
        public string ImageType { get; set; }
        public string InstanceCreationDate { get; set; }
        public string InstanceCreationTime { get; set; }
        public string AcquisitionDate { get; set; }
        public string AcquisitionTime { get; set; }
        public string SamplesPerPixel { get; set; }
        public string PhotometricInterpretation { get; set; }
        public string Rows { get; set; }
        public string Columns { get; set; }
        public string PixelAspectRatio { get; set; }
        public string BitsAllocated { get; set; }
        public string BitsStored { get; set; }
        public string HighBit { get; set; }
        public string PixelRepresentation { get; set; }
        public string WindowCenter { get; set; }
        public string WindowWidth { get; set; }
        public string StudyInstanceUID { get; set; }
        public string SeriesInstanceUID { get; set; }
        public string SOPInstanceUID { get; set; }
        public string AETitle { get; set; }
        public string AdjustedWindowWidth { get; set; }
        public string AdjustedWindowCenter { get; set; }
        public string MaxGrayscaleValue { get; set; }
        public string AdjustedGamma { get; set; }
        public string TimeStudyFirstOpened { get; set; }
        public string TimeReportApproved { get; set; }
        public string InstitutionName { get; set; }
    }
}
