USE [master]
GO

/****** Object:  Database [AXTDataLoad]    Script Date: 20/08/2020 10:43:47 ******/
CREATE DATABASE [AXTDataLoad]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AXTDataLoad', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\AXTDataLoad.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AXTDataLoad_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\AXTDataLoad_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AXTDataLoad].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AXTDataLoad] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AXTDataLoad] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AXTDataLoad] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AXTDataLoad] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AXTDataLoad] SET ARITHABORT OFF 
GO

ALTER DATABASE [AXTDataLoad] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AXTDataLoad] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AXTDataLoad] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AXTDataLoad] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AXTDataLoad] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AXTDataLoad] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AXTDataLoad] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AXTDataLoad] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AXTDataLoad] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AXTDataLoad] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AXTDataLoad] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AXTDataLoad] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AXTDataLoad] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AXTDataLoad] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AXTDataLoad] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AXTDataLoad] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AXTDataLoad] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AXTDataLoad] SET RECOVERY FULL 
GO

ALTER DATABASE [AXTDataLoad] SET  MULTI_USER 
GO

ALTER DATABASE [AXTDataLoad] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AXTDataLoad] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AXTDataLoad] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AXTDataLoad] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AXTDataLoad] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AXTDataLoad] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AXTDataLoad] SET  READ_WRITE 
GO


